### ISSUE TITLE
Checkpoint Harmony Endpoint and Rapid7 IDR Agent support

### ISSUE THREAD

**Issue by mosajjal** [tsale/EDR-Telemetry#104]
Hi, 

are there any plans to support these two products? If there's any appetite I'm happy to submit a PR

**Comment by tsale** [comment]
Please see if those EDRs follow eligibility criteria here: https://www.edr-telemetry.com/eligibility.html

If they do, please see this page that explains how to contribute: https://www.edr-telemetry.com/contribute.html
