### ISSUE TITLE
Kaspersky EDR

### ISSUE THREAD

**Issue by MrGoldenpioche** [tsale/EDR-Telemetry#106]
Hello. I think it could be useful to test the telemetry of Kaspersky EDR. I use it and I want to be able to compare it with other solution. I can provide you all information you need if you want.

**Comment by tsale** [comment]
Please see if those EDRs follow eligibility criteria here: https://www.edr-telemetry.com/eligibility.html

If they do, please see this page that explains how to contribute: https://www.edr-telemetry.com/contribute.html
