### ISSUE TITLE
Windows Telemetry: Services

### ISSUE THREAD

**Issue by bmmojo** [tsale/EDR-Telemetry#109]
EDR Telemetry Project: Windows | Microsoft Defender for Endpoint

MDE triggers alerts on new service creation.
You can search for it in Advanced Hunting/**DeviceEvents** table. 

```
DeviceEvents
| where ActionType == "ServiceInstalled"
| where FileName == "File"
| project DeviceName, ActionType, FileName, FolderPath, ProcessCommandLine, AdditionalFields
```

![ServiceCreation_1](https://github.com/user-attachments/assets/48f33c1c-0ad6-45ee-9cb1-97168483e201)
![ServiceCreation_2](https://github.com/user-attachments/assets/d697cfa8-3cd7-430a-922b-ead5ca5f74df)
![ServiceCreation_3](https://github.com/user-attachments/assets/a8ae3493-1f73-41b5-939e-2e7e89b720d9)

MDE collects data on service modification but does not trigger alert on service modification to my knowledge. 

- If I am wrong please post in this thread and let me know.

You can search for it in Advanced Hunting/**DeviceRegistryEvents** table.

```
DeviceRegistryEvents
| where Timestamp between (datetime(yyyy-mm-dd hh:mm:ss) .. datetime(yyyy-mm-dd hh:mm:ss)))
| where DeviceName == "Device"
| where ActionType contains "Registry"
| where RegistryKey == "HKEY_LOCAL_MACHINE\\SYSTEM\\ControlSet001\\Services\\ServiceName"
| project Timestamp, ActionType, RegistryKey, RegistryValueType, RegistryValueName, RegistryValueData, PreviousRegistryKey, PreviousRegistryValueName, PreviousRegistryValueData
```

![ServiceModification](https://github.com/user-attachments/assets/4fa05b51-3289-4afd-a967-a06744d28646)
![ServiceModification_2](https://github.com/user-attachments/assets/b593123c-d9ae-43f4-9ef3-a046ee7e1833)

As for Service Deletion, based on my research you can't search for service deletion in MDE/Advanced Hunting. I also haven't seen an alert triggered when a service has been deleted.

**Comment by tsale** [comment]
We do not take events that are generated as part of detections into consideration. Aditionally, we do not count telemetry from inferring events. This is mentioned here: https://www.edr-telemetry.com/eligibility.html
