### ISSUE TITLE
File Opened - Crowdstrike

### ISSUE THREAD

**Issue by NicolasSchn** [tsale/EDR-Telemetry#12]
Hello, 

Regarding Crowdstrike telemetry, some events are generated only when EDR detects suspicious behavior in the same process tree (Event FileOpenInfo related to File Opened operation for example).

This does not mean that the box should be red, but it may be useful to add if a condition is necessary for the generation of the event.

**Comment by inodee** [comment]
Hey @NicolasSchn, that claim seems to be valid!

Since we are here, any other cases that applies as well? We are happy to update to 'Partially Implemented' (amber icon) or wait for a PR from your side. Many thanks!

**Comment by jbfuzier** [comment]
> Hey @NicolasSchn, that claim seems to be valid!
> 
> Since we are here, any other cases that applies as well? We are happy to update to 'Partially Implemented' (amber icon) or wait for a PR from your side. Many thanks!

Hello,

This apply to any file events. Basically the sensor send only file related events that is deems suspicious based on some proprietary criterias.
Simple test, create a txt file with notepad, you should not see it in the telemetry.
