### ISSUE TITLE
[Feature Request] - Telemetry-generator - Check for an existing installation of Invoke-AtomicRedTeam

### ISSUE THREAD

**Issue by ScioShield** [tsale/EDR-Telemetry#22]
First thanks for all the handwork with this project. 

For v0.2 of the `telemetry-generator.ps1` would it be possible to add a check if `Invoke-AtomicRedTeam` is already installed? 
Could work something like so 

```
...
# Function that checks if Invoke-AtomicRedTeam is already installed
function Check-ARTInstalled {
    try {
        Get-Command Invoke-AtomicTest -ErrorAction Stop | Out-Null
        return $true
    }
    catch {
        return $false
    }
}
...
# Install Invoke-Atomic if not already installed
if (-not (Check-ARTInstalled)) {
    Install-ART
}
...
```

Thanks again!

**Comment by ScioShield** [comment]
Hi I've just retested and since you are not using the '-Force' parameter flag it doesn't change existing installations. Please feel free to close this FR. 
My apologies. :)

**Comment by tsale** [comment]
No problem! Thanks for looking into it.
