### ISSUE TITLE
Add Wazuh!

### ISSUE THREAD

**Issue by y0d4a** [tsale/EDR-Telemetry#26]
Please add wazuh in this list, it is open source edr/xdr....

**Comment by inodee** [comment]
Hey @y0d4a 

There were 2 new products added by community members recently:

https://github.com/tsale/EDR-Telemetry/pulls?q=is%3Apr+is%3Aclosed

Happy to evaluate your submission.

Regards
Alex

**Comment by tsale** [comment]
We're planing to have them all, but we don’t have access to them all 🙂 Any contributions from the community is appreciated.

Wazuh is in the list of EDRs that we are planning to have for sure, but please feel free to create a submission for it.
