### ISSUE TITLE
Color blindness

### ISSUE THREAD

**Issue by Andynam0** [tsale/EDR-Telemetry#50]
Can you use colors, and or monikers that make it easier to tell who has what :) To some of us, Reds/Greens are not great to use for this. Standard black Y/N/P/? (yes no partial unknown) would work too. Pink/Red/Orange are hard to tell apart for my collogues. :) Love the repo!

**Comment by tsale** [comment]
Thank you very much @Andynam0 for this feedback. What if we add another table for colorblind individuals? Would that work? Thanks again!

**Comment by Andynam0** [comment]
That could work, or if the contrast of the colors could be more "severe", Bright Red, Dark Orange, Bright Yellow, Dark Green
I found a "contrast checker" that may help. https://webaim.org/resources/contrastchecker/
Thanks for taking the time to write back so quickly!
