### ISSUE TITLE
Missing Task start and Service start telemetries 

### ISSUE THREAD

**Issue by subvert0r** [tsale/EDR-Telemetry#69]
These telemetries are missing from the comparison:

```
Task Start
Service Start
```

If we are going to even include deletion of these, then surely starting it would be included in the comparison..

**Comment by tsale** [comment]
They are secondary but yes, they should be included. The problem is that for this to happen, we need to update all vendors and that would take time. 

Feel free to start the process by creating a PR that would include service and scheduled task start/stopped.
