### ISSUE TITLE
Possible "via Event Logs" Categorization Issue

### ISSUE THREAD

**Issue by MarDeus** [tsale/EDR-Telemetry#81]
I wanted to inquire about the usage of "via Event Logs" within the EDR Telemetry Table. Specifically how one EDR could support the ingestion of a Windows Event Log for a sub-category, but another sub-category that other EDRs allow for "via Event Logs", can't be ingested?

For instance, Elastic EDR shows within the Telemetry Feature Category field that "User Account Activity" can be collected via Windows Event Logs. However, for the Sub-Category "Driver Unloaded", you show "No", although for Uptycs, you show it accomplishes it "via Event Logs". I was wondering what the difference could be considering both show the capability for Event Log ingestion, but only one EDR has the capability marked "via Event Logs".

Another Telemetry Feature Category for Elastic is "WMI Activity". Qualys shows the capability to use "via Windows Event Logs". Wouldn't this replicate across any EDR that has Event Log ingestion capabilities?

**Comment by joshlemon-uptycs** [comment]
For Uptycs, it pulls the Event log into the platform and stores it once the Driver Unloaded Event occurs in the Event Logs. I'm unsure about Elasic, but it may not be counted if Elasitc doesn't pull that Event ID into their EDR.

**Comment by MarDeus** [comment]
Filebeat's capabilities entail forwarding ANY event logs you target within your xml configuration. Including Windows Service application logs, etc.

**Comment by tsale** [comment]
We've recently made some clarifications regarding what constitutes Via EventLogs and how we assess EDRs based on this category. These refinements ensure more precise evaluations of EDR capabilities and align with updated scoring criteria.
From our latest blog post, [EDR Telemetry Project: Exciting New Updates and Insights](https://kostas-ts.medium.com/edr-telemetry-project-exciting-new-updates-and-insights-2feb693bb4ba?sk=8126c3a8943119e0c28825cc846e6143), here’s a summary of the key change:

We’ve updated the scoring for Via EventLogs from 0.75 to 0.5 to reflect our refined definitions better. The `Via EventLogs` now specifically refers to data collected from Windows Event Logs directly if these logs exist in the system.
