### ISSUE TITLE
Test Telemetry Linux - Crowdstrike (on debian)

### ISSUE THREAD

**Issue by mthcht** [tsale/EDR-Telemetry#86]
@tsale 
The result of my test:

[
[telemetry_debian_edr_crowdstrike_test.md](https://github.com/user-attachments/files/17845295/telemetry_debian_edr_crowdstrike_test.md)
](url)

**Comment by tsale** [comment]
Thanks @mthcht! I have a quick question: Could you please let me know if you can see any of the events below?

```
User Logon
User Logoff
Logon Failed
Script Content (The content of the script that is being executed)
```

**Comment by tsale** [comment]
Thanks @mthcht! In terms of the script content, this is good. I would still count that.

**Comment by mthcht** [comment]
@tsale i added a scheduled task manually with a crontab command since the script failed and no dedicated event for this, only visible in process execution 'ProcessRollup2'

**Comment by tsale** [comment]
Thank you for the clarification @mthcht!
