### ISSUE TITLE
Weight based Scoring

### ISSUE THREAD

**Issue by Gandalf098** [tsale/EDR-Telemetry#92]
not all telemetry was born equal, some are more useful than others, some are available through other means such as native logging

I think here maybe we can discuss a detailed method to scoring

**Comment by tsale** [comment]
All telemetry categories and sub-categories have assigned weights. Depending on who you ask, opinions about the weight scoring for Windows events will vary.

I don't believe this issue needs to remain open unless you have a proposal for improvement.
